import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  flex1: {flex: 1},
  ph16: {
    paddingHorizontal: 16,
  },
  jcac: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatList: {
    gap: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  flatListImgs: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: 'white',
    borderWidth: 0.2,
    height: 5,
    width: 5,
    borderRadius: 5,
  },
  title: {color: 'white', fontSize: 27, lineHeight: 30},
  price: {
    width: 123,
    height: 35,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: '#314FF6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    color: 'white',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18.9,
    letterSpacing: -0.015,
    textAlign: 'left',
  },
  separator: {
    borderBottomColor: 'white',
    borderBottomWidth: 0.4,
    marginHorizontal: 30,
  },
  topImg: {
    width: 214,
    height: 180,
    backgroundColor: 'white',
    borderRadius: 30,
  },
  containerB: {flex: 0.55, marginBottom: 20},
  subImgs: {
    height: 62,
    width: 75,
    borderRadius: 10,
  },
  imageContainer: {flexDirection: 'row', justifyContent: 'center', gap: 20},
  bottomImage: {
    height: 54,
    width: 54,
    borderRadius: 27,
    borderColor: 'white',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomSubTitle: {
    color: 'white',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 18.9,
    letterSpacing: -0.015,
    textAlign: 'left',
  },
  bottomTextBold: {
    color: 'white',
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 24.3,
    letterSpacing: -0.015,
    textAlign: 'left',
  },
  bottomContainer: {
    flex: 0.5,
    paddingHorizontal: 16,
    justifyContent: 'space-around',
    paddingVertical: 10,
  },
  buttonContainer: {
    width: 327,
    height: 50,
    borderRadius: 60,
    borderWidth: 1,
    backgroundColor: '#314FF6',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonTitle: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 30,
    letterSpacing: -0.015,
    textAlign: 'left',
    color: 'white',
  },
  subTitle: {
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 30,
    letterSpacing: -0.015,
    textAlign: 'left',
    color: 'white',
  },
});
